config:
  cloud-config:
    users:
    - name: root
      passwd: root
  elemental:
    install:
      poweroff: true
      device: /dev/sda
    registrration:
      emulate-tpm: true
      emulated-tpm-seed: -1