kind: GitRepo
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: awsgov-shared-cluster-loader
  namespace: fleet-local
spec:
  repo: https://github.com/bcdurden/multicloud-rancher-demo.git
  branch: main  
  targets:
  - clusterName: local
  paths:
  - "./gitops/clusters/awsgov/shared"