cloudprovider: harvester
cloudCredentialSecretName: cattle-global-data:cc-5gm5v
cluster:
  annotations: {}
  labels:
    environment: sandbox
    cluster_name: alpha
    location: hx90
  name: sandbox-alpha
kubernetesVersion: v1.24.7+k3s1 # v1.24.2+rke2r1
monitoring:
  enabled: false
rke:
  localClusterAuthEndpoint:
    enabled: false
nodepools:
- etcd: true
  controlplane: true
  worker: true
  displayName: control-plane-nodes
  name: control-plane-sandbox-pool
  labels: {}
  taints: {}
  quantity: 1
  paused: false
  diskSize: 40
  diskBus: virtio
  cpuCount: 2
  memorySize: 4
  networkName: default/sandbox
  networkType: dhcp
  imageName: default/ubuntu-2004
  vmNamespace: default
  sshUser: ubuntu
- etcd: false
  controlplane: false
  worker: true
  displayName: worker-nodes
  name: worker-sandbox-pool
  labels: {}
  taints: {}
  quantity: 2
  paused: false
  diskSize: 40
  diskBus: virtio
  cpuCount: 2
  memorySize: 4
  networkName: default/sandbox
  networkType: dhcp
  imageName: default/ubuntu-2004
  vmNamespace: default
  sshUser: ubuntu
