#cloud-config
package_update: true
write_files:
- path: /etc/rancher/rke2/config.yaml
  owner: root
  content: |
    token: my-shared-token
    tls-san:
      - rke2-gpu-cluster-cp-0
      - rke2-gpu-cluster-cp
      - 10.10.5.4
- path: /etc/hosts
  owner: root
  content: |
    127.0.0.1 localhost
    127.0.0.1 rke2-gpu-cluster-cp-0
    127.0.0.1 rke2-gpu-cluster-cp
packages:
  - qemu-guest-agent
runcmd:
  - - systemctl
    - enable
    - --now
    - qemu-guest-agent.service
  - curl -sfL https://get.rke2.io | INSTALL_RKE2_VERSION="v1.24.3+rke2r1" sh -
  - mkdir -p /var/lib/rancher/rke2/server/manifests/
  - >-
    wget https://kube-vip.io/manifests/rbac.yaml -O
    /var/lib/rancher/rke2/server/manifests/kube-vip-rbac.yaml
  - >-
    curl -sL kube-vip.io/k3s |  vipAddress=10.10.5.4 vipInterface=enp1s0 sh |
    sudo tee /var/lib/rancher/rke2/server/manifests/vip.yaml
  - systemctl enable rke2-server.service
  - systemctl start rke2-server.service
ssh_authorized_keys:
  - ssh-rsa
    AAAAB3NzaC1yc2EAAAADAQABAAACAQDZk5zkAj2wbSs1r/AesCC7t6CtF6yxmCjlXgzqODZOujVscV6PZzIti78dIhv3Yqtii/baFH0PfqoHZk9eayjZMcp+K+6bi4lSwszzDhV3aGLosPRNOBV4uT+RToEmiXwPtu5rJSRAyePu0hdbuOdkaf0rGjyUoMbqJyGuVIO3yx/+zAuS8hFGeV/rM2QEhzPA4QiR40OAW9ZDyyTVDU0UEhwUNQESh+ZM2X9fe5VIxNZcydw1KGwzj8t+6WuYBFvPKYR5sylAnocBWzAGKh+zHgZU5O5TwC1E92uPgUWNwMoFdyZRaid0sKx3O3EqeIJZSqlfoFhz3Izco+QIx4iqXU9jIVFtnTb9nCN/boXx7uhCfdaJ0WdWQEQx+FX092qE6lfZFiaUhZI+zXvTeENqVfcGJSXDhDqDx0rbbpvXapa40XZS/gk0KTny2kYXBATsUwZqmPpZF9njJ+1Hj/KSNhFQx1LcIQVvXP+Ie8z8MQleaTTD0V9+Zkw2RBkVPYc5Vb8m8XCy1xf4DoP6Bmb4g3iXS17hYQEKj1bfBMbDfZdexbSPVOUPXUMR2aMxz8R3OaswPimLmo0uPiyYtyVQCuJu62yrao33knVciV/xlifFsqrNDgribDNr4RKnrIX2eyszCiSv2DoZ6VeAhg8i6v6yYL7RhQM31CxYjnZK4Q==
    briandurden@Brians-Air.homenetwork
