kind: GitRepo
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: sandbox-cluster-loader
  namespace: fleet-local
spec:
  repo: https://git.sienarfleet.systems/gitea/multicloud-rancher-demo.git
  branch: main  
  targets:
  - clusterName: local
  paths:
  - "./gitops/clusters/harvester1/sandbox"