kind: GitRepo
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: log-forwarder
  namespace: fleet-default
spec:
  repo: https://github.com/bcdurden/demo-multicloud.git
  branch: main

  # To target specific clusters, uncomment this block
  targets:
  - clusterSelector:
      matchLabels:
        environment: shared
  - clusterSelector:
      matchLabels:
        environment: dev
  - clusterSelector:
      matchLabels:
        environment: sandbox
  - clusterSelector:
      matchLabels:
        environment: prod

  paths:
  - "./gitops/apps/logging/promtail"