kind: GitRepo
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: registry
  namespace: fleet-default
spec:
  repo: https://github.com/bcdurden/demo-multicloud.git
  branch: main
  
  targets:
  - clusterSelector:
      matchLabels:
        environment: shared
        cluster_name: services

  paths:
  - "./gitops/apps/registry/"