kind: GitRepo
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: secret-store
  namespace: fleet-default
spec:
  repo: https://github.com/bcdurden/multicloud-rancher-demo.git
  branch: main
  
  targets:
  - clusterSelector:
      matchLabels:
        environment: shared

  paths:
  - "./gitops/apps/secret_store/"